import "./index.css";
import React from 'react';
import {Loader} from '../Loader/index';


// Exercise
// TODO include the Avatar component you wrote, and use it in the ChatThread.Item component
// TODO create one ChatItem per chat passed in
// TODO handle the case where chats are empty by rendering the list generated by 'emptyThread' if chats is empty
export const ChatThread = ({ chats }) => (
  <ul className="ChatThread">
    FIXME
  </ul>
)


// you'll note you can group related functional components by making them properties of another component, if you wish
ChatThread.Item = ({ chat }) => (
  <li className="ChatThreadItem"
      >
    TODO
    <span className="ChatThreadMessage">
    </span>
  </li>
)


function emptyThread() {
  return [
    {
      id: "empty",
      message: "Say something to break the ice!",
      avatar: "penguin",
    }
  ]
}
